services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=purchases'
      - 'POSTGRES_PASSWORD=docker'
      - 'POSTGRES_USER=docker'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '5672:5672'
      - "15672:15672"
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
